### ISSUE TITLE
Obter a organização "patriarca" do usuário de forma implícita

### ISSUE THREAD

**Issue by fontourafernando** [prodest/processo-eletronico#20]
Obter a organização "patriarca" do usuário de forma implícita, capturando-a através das informações do usuário logado (Acesso Cidadão).

**Comment by brenowschneider** [comment]
Além disso, suprimir "organizacoes-processo" da url.

**Comment by brenowschneider** [comment]
Issue cadastrada no repositorio errado. Esse caso está sendo tratado na issue #98 do processo-eletronico-web-api
